apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: redis
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
